const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json'
const endpointsFiles = ['./src/routes.ts']

const doc = {
    info: {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3333",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    definitions: {
        AddUser: {
            $username: "Jhon Doe",
            $email: "jhon@doe.com",
            $password: ""
        },
        AddMessage: {
            $user_id: "977d6055-4bfa-4cd1-bae4-8e0378b89464",
            $text: "Mensagem do usuário",
            admin_id: ""
        },
        AddSettings: {
            $chat: false,
            $username: "jhonDoe"
        }
    }
}

swaggerAutogen(outputFile, endpointsFiles, doc)